[package]
name = "ransomware"
version = "0.1.0"
edition = "2024"

[dependencies]
aes-gcm = "0.10.3"
rand = "0.9.1"
pbkdf2 = { version = "0.12.2", features = ["simple"] }
# rand_core = { version = "0.6", features = ["std"] }
